(deftheme pumba
  "Created 2011-11-29.")

(custom-theme-set-faces
 'pumba
 '(cursor ((((class color) (min-colors 89)) (:background "#656565"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#444444" :foreground "#857b6f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(escape-glyph ((t (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(font-lock-constant-face ((t (:foreground "#e5786d"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-string-face ((t (:foreground "light goldenrod"))))
 '(font-lock-type-face ((t (:foreground "burlywood1"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold))))
 '(magit-item-highlight ((t (:inherit region))))
 '(diff-added ((t (:foreground "#cae682"))))
 '(diff-removed ((t (:foreground "#e5786d"))))
 '(erc-notice-face ((t (:foreground "#92a65e"))))
 '(erc-timestamp-face ((t (:foreground "#ccaa8f" :weight bold))))
 '(font-lock-variable-name-face ((t (:background "#242424" :foreground "#f6f3e8"))))
 '(default ((((class color) (min-colors 89)) (:background "#242424" :foreground "#f6f3e8"))))
 '(error ((t (:foreground "#e5786d" :weight bold))))
 '(success ((t (:foreground "#cae682" :weight bold)))))

(provide-theme 'pumba)
