(defun color-theme-autumn ()
  "Color theme by Jose A Ortega Ruiz, created 2002-08-13."
  "Color theme by Aleix Conchillo Flaque, modified 2005-08-01."
  (interactive)
  (color-theme-install
   '(color-theme-autumn
     ((mouse-color . "white")
      (background-color . "grey25")
      (background-mode . dark)
      (border-color . "Grey")
      (cursor-color . "Grey")
      (foreground-color . "beige"))
     (default ((t (nil))))
     (mouse ((t (:background "white"))))
     (Info-title-1-face ((t (:bold t :weight bold :family "terminus" :height 1.728))))
     (Info-title-2-face ((t (:bold t :family "terminus" :weight bold :height 1.44))))
     (Info-title-3-face ((t (:bold t :weight bold :family "terminus" :height 1.2))))
     (Info-title-4-face ((t (:bold t :family "terminus" :weight bold))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t :family "fixed"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :foreground "beige" :weight bold))))
     (border ((t (:background "white"))))
     (calendar-today-face ((t (:underline t :family "fixed"))))
     (comint-highlight-input ((t (:italic t :slant italic))))
     (comint-highlight-prompt ((t (:bold t :weight bold :foreground "white"))))
     (compilation-error ((t (:foreground "orange"))))
     (compilation-info ((t (:foreground "orange"))))
     (cperl-array-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
     (cursor ((t (:background "Grey"))))
     (custom-button-face ((t (:foreground "gainsboro"))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment-face ((t (:italic t :slant italic :background "gainsboro"))))
     (custom-comment-tag-face ((t (:foreground "gainsboro"))))
     (custom-documentation-face ((t (:foreground "light blue"))))
     (custom-face-tag-face ((t (:underline t :family "fixed"))))
     (custom-group-tag-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t :family "fixed"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "gainsboro"))))
     (custom-saved-face ((t (:underline t :family "fixed"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (:foreground "sienna"))))
     (custom-variable-button-face ((t (:bold t :underline t :family "fixed" :weight bold))))
     (custom-variable-tag-face ((t (:foreground "turquoise"))))
     (cvs-filename-face ((t (:foreground "burlywood"))))
     (cvs-header-face ((t (:foreground "white"))))
     (cvs-marked-face ((t (:foreground "light salmon"))))
     (cvs-need-action-face ((t (:foreground "bisque"))))
     (cvs-unknown-face ((t (:foreground "light salmon"))))
     (diary-face ((t (:foreground "red"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:underline t :family "fixed" :height 1.0))))
     (ecb-directories-general-face ((t (:height 1.0))))
     (ecb-directory-face ((t (:background "grey50" :height 1.0))))
     (ecb-history-face ((t (:background "grey50" :height 1.0))))
     (ecb-history-general-face ((t (:height 1.0))))
     (ecb-method-face ((t (:background "grey50" :height 1.0))))
     (ecb-methods-general-face ((t (:height 1.0))))
     (ecb-source-face ((t (:background "grey50" :height 1.0))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "burlywood" :height 1.0))))
     (ecb-sources-general-face ((t (:height 1.0))))
     (ecb-token-header-face ((t (:foreground "black" :background "burlywood"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (emacs-wiki-bad-link-face ((t (:foreground "light salmon" :weight bold))))
     (emacs-wiki-header-1 ((t (:bold t :weight bold :height 1.2 :family "terminus"))))
     (emacs-wiki-header-2 ((t (:bold t :weight bold :height 1.2 :family "terminus"))))
     (emacs-wiki-header-3 ((t (:height 120 :family "modd"))))
     (emacs-wiki-header-4 ((t (:height 120 :family "modd"))))
     (emacs-wiki-header-5 ((t (:height 120 :family "modd"))))
     (emacs-wiki-header-6 ((t (:height 120 :family "modd"))))
     (emacs-wiki-link-face ((t (:foreground "burlywood" :family "modd"))))
     (erc-action-face ((t (:foreground "burlywood"))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:foreground "burlywood"))))
     (erc-default-face ((t (:foreground "Grey"))))
     (erc-direct-msg-face ((t (:foreground "bisque"))))
     (erc-error-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (erc-highlight-face ((t (:foreground "lightsalmon"))))
     (erc-input-face ((t (:foreground "bisque"))))
     (erc-inverse-face ((t (:background "grey"))))
     (erc-nick-default-face ((t (:foreground "burlywood" :weight bold :bold t))))
     (erc-notice-face ((t (:foreground "grey50"))))
     (erc-pal-face ((t (:foreground "burlywood"))))
     (erc-prompt-face ((t (:foreground "bisque"))))
     (erc-timestamp-face ((t (:foreground "bisque"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "medium purple" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "dim gray"))))
     (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product-face ((t (:foreground "light steel blue"))))
     (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "gold"))))
     (eshell-ls-symlink-face ((t (:foreground "white"))))
     (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
     (eshell-prompt-face ((t (:foreground "burlywood" :family "modd"))))
     (excerpt ((t (:italic t :slant italic))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :family "fixed" :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :family "fixed" :weight bold))))
     (font-latex-bold-face ((t (:bold t :foreground "dark khaki" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "khaki" :slant italic))))
     (font-latex-math-face ((t (:foreground "burlywood"))))
     (font-latex-sedate-face ((t (:foreground "LightGray"))))
     (font-latex-string-face ((t (:foreground "LightSalmon"))))
     (font-latex-title-1-face ((t (:bold t :foreground "peru"))))
     (font-latex-title-2-face ((t (:bold t :foreground "peru"))))
     (font-latex-title-3-face ((t (:foreground "peru"))))
     (font-latex-title-4-face ((t (:foreground "peru"))))
     (font-latex-warning-face ((t (:foreground "orange"))))
     (font-lock-builtin-face ((t (:foreground "bisque"))))
     (font-lock-comment-face ((t (:foreground "slate gray"))))
     (font-lock-constant-face ((t (:foreground "antiquewhite"))))
     (font-lock-doc-face ((t (:foreground "gray60"))))
     (font-lock-doc-string-face ((t (:foreground "gray60"))))
     (font-lock-function-name-face ((t (:foreground "burlywood"))))
     (font-lock-keyword-face ((t (:foreground "Khaki"))))
     (font-lock-reference-face ((t (:foreground "dark khaki"))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "bisque"))))
     (font-lock-variable-name-face ((t (:foreground "white"))))
     (font-lock-warning-face ((t (:bold t :foreground "light salmon"))))
     (fringe ((t (:background "grey20"))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "LightSalmon"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "Khaki"))))
     (gnus-cite-face-3 ((t (:foreground "Coral"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t :family "fixed"))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :family "fixed" :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold :family "fixed"))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic :family "fixed"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-mail-1-face ((t (:foreground "antiquewhite" :family "modd"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-mail-2-face ((t (:foreground "burlywood" :family "modd"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "grey" :family "modd"))))
     (gnus-group-mail-3-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "grey" :family "modd"))))
     (gnus-group-mail-low-face ((t (:foreground "grey" :family "modd"))))
     (gnus-group-news-1-empty-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-news-1-face ((t (:foreground "antiquewhite" :family "modd"))))
     (gnus-group-news-2-empty-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-news-2-face ((t (:foreground "grey" :family "modd"))))
     (gnus-group-news-3-empty-face ((t (:foreground "bisque" :family "modd"))))
     (gnus-group-news-3-face ((t (:foreground "burlywood" :family "modd" :bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine" :family "modd"))))
     (gnus-group-news-4-face ((t (:foreground "Aquamarine" :family "modd"))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine" :family "modd"))))
     (gnus-group-news-5-face ((t (:foreground "MediumAquamarine" :family "modd"))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine" :family "modd"))))
     (gnus-group-news-6-face ((t (:foreground "MediumAquamarine" :family "modd"))))
     (gnus-group-news-low-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3" :family "neep"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan" :weight bold :family "neep"))))
     (gnus-header-name-face ((t (:bold t :foreground "LightBlue" :weight bold :family "neep"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "MediumAquamarine" :weight bold :family "neep"))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold :family "neep"))))
     (gnus-signature-face ((t (:foreground "Grey" :family "modd"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "Black" :foreground "GoldenRod"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "Grey" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "DimGray" :slant italic))))
     (gnus-summary-low-read-face ((t (:foreground "slate gray"))))
     (gnus-summary-low-ticked-face ((t (:foreground "burlywood"))))
     (gnus-summary-low-unread-face ((t (:foreground "LightGray"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "burlywood"))))
     (gnus-summary-normal-read-face ((t (:foreground "Khaki"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "IndianRed"))))
     (gnus-summary-normal-unread-face ((t (:foreground "beige"))))
     (gnus-summary-selected-face ((t (:foreground "LightSalmon"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey10" :foreground "grey90" :box nil))))
     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
     (highline-face ((t (:background "DeepSkyBlue4"))))
     (html-helper-italic-face ((t (:foreground "LightGray" :italic t :slant italic))))
     (html-tag-face ((t (:foreground "burlywood"))))
     (holiday-face ((t (:background "LightSalmon"))))
     (info-header-node ((t (:bold t :weight bold))))
     (info-header-xref ((t (:bold t :weight bold :foreground "burlywood"))))
     (info-menu-5 ((t (:underline t :family "fixed"))))
     (info-menu-header ((t (:bold t :family "terminus" :weight bold))))
     (info-node ((t (:bold t :weight bold))))
     (info-xref ((t (:bold t :foreground "burlywood" :weight bold))))
     (isearch ((t (:background "slate blue"))))
     (isearch-lazy-highlight-face ((t (:background "paleturquoise4"))))
     (italic ((t (:foreground "sky blue"))))
     (jde-java-font-lock-link-face ((t (:underline t :family "modd"))))
     (jde-java-font-lock-package-face ((t (:foreground "grey"))))
     (makefile-space-face ((t (:background "grey"))))
     (margin-face ((t (:background "red"))))
     (menu ((t (:background "grey20" :foreground "bisque"))))
     (message-cited-text-face ((t (:foreground "LightSalmon"))))
     (message-header-cc-face ((t (:foreground "light cyan"))))
     (message-header-name-face ((t (:foreground "LightBlue"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "MediumAquamarine"))))
     (message-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-xheader-face ((t (:foreground "MediumAquamarine"))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "chocolate"))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LightGray"))))
     (mmm-comment-submode-face ((t (:background "SkyBlue"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "gray85"))))
     (mmm-init-submode-face ((t (:background "gray50"))))
     (mmm-output-submode-face ((t (:background "Plum"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     (mode-line ((t (:background "grey20" :foreground "wheat" :box (:line-width 1 :style nil)))))
     (modeline-buffer-id ((t (:background "slate blue" :foreground "beige"))))
     (modeline-mousable ((t (:background "slate blue" :foreground "light cyan"))))
     (modeline-mousable-minor-mode ((t (:background "slate blue" :foreground "wheat"))))
     (region ((t (:background "DarkSlateBlue"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "steel blue"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (show-paren-match-face ((t (:background "light slate blue" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "red" :foreground "white"))))
     (speedbar-button-face ((t (:foreground "seashell2"))))
     (speedbar-directory-face ((t (:foreground "seashell3"))))
     (speedbar-file-face ((t (:foreground "seashell4"))))
     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
     (speedbar-selected-face ((t (:foreground "seashell1" :underline t :family "fixed"))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "antique white"))))
     (svn-status-filename-face ((t (:foreground "grey"))))
     (svn-status-directory-face ((t (:weight bold :foreground "white" :bold t))))
     (svn-status-marked-face ((t (:foreground "light salmon"))))
     (svn-status-modified-external-face ((t (:foreground "bisque"))))
     (tla-archive-name ((t (:foreground "peru"))))
     (tla-location-local ((t (:foreground "grey60"))))
     (tla-location-sftp ((t (:foreground "grey60"))))
     (tla-marked ((t (:bold t :foreground "beige"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t :family "fixed"))))
     (variable-pitch ((t (:family "terminus"))))
     (w3m-anchor-face ((t (:foreground "LightSalmon" :family "modd"))))
     (w3m-arrived-anchor-face ((t (:foreground "burlywood"))))
     (w3m-bold-face ((t (:bold t :weight bold :family "fixed"))))
     (w3m-current-anchor-face ((t (:bold t :underline t :weight bold :family "modd"))))
     (w3m-form-button-face ((t (:background "grey20" :foreground "lightyellow" :box (:line-width 1 :style nil)))))
     (w3m-form-button-mouse-face ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed-face ((t (:background "grey20" :foreground "lightyellow" :box (:line-width 2 :style pressed-button)))))
     (w3m-form-face ((t (:foreground "lightyellow" :underline t :family "fixed"))))
     (w3m-header-line-location-content-face ((t (:background "grey15" :foreground "LightGoldenrod"))))
     (w3m-header-line-location-title-face ((t (:background "grey15" :foreground "LightGoldenrod"))))
     (w3m-history-current-url-face ((t (:underline t :family "fixed"))))
     (w3m-image-face ((t (:foreground "grey60"))))
     (w3m-tab-background-face ((t (:background "grey20" :foreground "gray"))))
     (w3m-tab-selected-face ((t (:background "grey20" :foreground "white" :box (:line-width 1 :style nil)))))
     (w3m-tab-selected-retrieving-face ((t (:background "gray20" :foreground "orange" :box (:line-width 1 :style nil)))))
     (w3m-tab-unselected-face ((t (:background "grey20" :foreground "gray50" :box (:line-width 1 :style nil)))))
     (w3m-tab-unselected-retrieving-face ((t (:background "Gray20" :foreground "OrangeRed" :box (:line-width 1 :style nil)))))
     (w3m-underline-face ((t (:underline t :family "fixed"))))
     (widget-button-face ((t (:bold t :weight bold))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "grey"))))
     (widget-field-face ((t (:background "gray30" :foreground "grey"))))
     (widget-inactive-face ((t (:foreground "gray70"))))
     (widget-single-line-field-face ((t (:background "dim grey" :foreground "wheat"))))
     (woman-bold-face ((t (:bold t :foreground "burlywood" :weight bold :family "fixed"))))
     (woman-italic-face ((t (:foreground "antiquewhite"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (zmacs-region ((t (:background "DarkSlateBlue")))))))
